### ISSUE TITLE
Collect the into about algos

### ISSUE THREAD

**Issue by ZeLebo** [ZeLebo/Timetable#27]
Надо почитать про варианты алгосов (их не так много) и накидать что-то на затычках

**Comment by Shreksatronik** [comment]
https://cyberleninka.ru/article/n/algoritm-sostavleniya-raspisaniya-zanyatiy-dlya-vysshih-uchebnyh-zavedeniy //Эта лучше
--------------------------------------------------------------------------------------------------------------------------------------------
https://cyberleninka.ru/article/n/kompleks-algoritmov-postroeniya-raspisaniya-vuza-chast-2-struktura-predstavleniya-dannyh-i-algoritm-postroenie-opornogo-resheniya/viewer
